apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  namespace: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/target: "${local_ip}"
spec:
  gatewayClassName: traefik
  listeners:
    - name: twintails-http
      protocol: HTTP
      hostname: "${base_hostname}"
      port: 80
      allowedRoutes:
        namespaces:
          from: All

    - name: twintails-https
      protocol: HTTPS
      hostname: "*.${base_hostname}"
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: twintailsare-moe-tls
            kind: Secret
