# yaml-language-server: $schema=https://raw.githubusercontent.com/kaasops/vector-operator/refs/heads/main/helm/charts/vector-operator/crds/observability.kaasops.io_clustervectorpipelines.yaml
apiVersion: observability.kaasops.io/v1alpha1
kind: ClusterVectorPipeline
metadata:
  name: cluster-logs
spec:
  sources:
    cluster-logs:
      type: "kubernetes_logs"
      auto_partial_merge: true
  sinks:
  #TODO: add victorialogs server
    console-test:
      type: "console"
      encoding:
        codec: "json"
      inputs:
        - cluster-logs