---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "^77.5.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-stack
        namespace: monitoring
      interval: 24h
  values:
    defaultRules:
      rules:
        windows: false
    
    windowsMonitoring:
      enabled: false
    
    prometheus-windows-exporter:
      prometheus:
        monitor:
          enabled: false

    alertmanager:
      alertmanagerSpec:
        secrets:
          - alertmanager-secrets
        alertmanagerConfiguration:
          name: global-alertmanager-config
      service:
        port: 9093