---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path-provisioner
  namespace: local-path-storage
spec:
  interval: 60m
  timeout: 3m
  retryInterval: 2m
  prune: true
  wait: true
  path: ./deploy
  sourceRef:
    kind: GitRepository
    name: local-path-provisioner
  patches:
    - patch: |-
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: local-path-config
          namespace: local-path-storage
        $patch: delete
      target:
        kind: ConfigMap
        name: local-path-config
        namespace: local-path-storage
    - patch: |
        - op: replace
          path: /spec/template/spec/volumes/0/configMap/name
          value: local-path-config
      target: 
        kind: Deployment
        name: local-path-provisioner
        namespace: local-path-storage