---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hdd-local-path
  annotations:
    defaultVolumeType: local
provisioner: rancher.io/local-path
parameters:
  nodePath: "${hdd_mountpoint}/container_store"
  pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete