apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
  labels:
    app: pihole
data:
  values.yaml: |-
    persistentVolumeClaim:
      enabled: false

    serviceDhcp:
      enabled: false

    dnsHostPort:
      enabled: true
      port: 53

    serviceDns:
      type: NodePort
      nodePort: "53"

    serviceWeb:
      http:
        enabled: true
      https:
        enabled: false
    
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    
    admin:
      enabled: true
      existingSecret: pihole-password
      passwordKey: "pihole-password"


