apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
  labels:
    app: pihole
data:
  values.yaml: |-
    persistentVolumeClaim:
      enabled: true
      storageClass: "hdd-local-path"

    serviceDhcp:
      enabled: false

    serviceDns:
      type: NodePort

    serviceWeb:
      http:
        enabled: true
      https:
        enabled: false
    
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    
    admin:
      enabled: true
      existingSecret: pihole-password
      passwordKey: "pihole-password"


