stores:
  yaml:
    indent: 2
creation_rules: 
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    age: >- 
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIORbL1oxobb9kacZtHn4eH/JXOnb/h9eJzukcNTVGkkZ 3vabun@pm.me,
      age15z7sk0c6teshxjaesjmvmthhwuhlfyucg8uxktazxvwcjtc8kvas8ft7k5
