apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secrets
  namespace: monitoring
stringData:
  telegram-bot-token: ENC[AES256_GCM,data:E1Rzm4hDOlG5owcAk0GQXeP5w0wFYR+xtGHN/Kdxv0CJeWDlP5BGnNAtfOCphQ==,iv:B8M6VWuM+KvkfGxq1hWomcy/YWTZFnietDOE7yYTd2E=,tag:d2UlXfxoAnNcThVNpuqTyw==,type:str]
type: Opaque
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIORbL1oxobb9kacZtHn4eH/JXOnb/h9eJzukcNTVGkkZ 3vabun@pm.me
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFZkU1BidyB0UCtD
        SEZsWHpsNEFYWnIyVkdIdTdrUXFiNGNJRE85Q1I4Q1hHcHBtWURBCnVSNytmQ3Zx
        MytGa3FsbWdUTUhQRmtTeDQyd1Y0S0R0dUFKbWRSZGR5bEkKLS0tIG5uUjl0QlRn
        M0FENDVnNngrQk9rMzM2Y29nU3ZWR3dzY3BSeEJhd2lLWk0Kfio8Fichg8N3jxIf
        eb2iQJspq+J+rVP13YSthEwV6cbRA/01z7aV0jrCY7nMsyxhDaeXS9uoe9WsImmo
        O7UBgg==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age15z7sk0c6teshxjaesjmvmthhwuhlfyucg8uxktazxvwcjtc8kvas8ft7k5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRmVtazJIMjZKUFhBdTQw
        VzZnUW1KTVFWYWhPVCtxYTF5NmNpWGF4eUdvCkdjaXY1N0JXb2tWNkpmaW10SDFS
        MTRzdzlVNUZPUHYzUmhYd04xNmt0dDQKLS0tIE1FblRiVENpbDFORUI0TStUUzBh
        ZUtBVllobm81M1Y1NnBLR3ZZUmtMalEKJPJ1AB8pDp9fLXBdhDN7bTMCo2PMgCQO
        l1od0QUtO/sQJfJOnJhk2BEA8h3XsjfKsW67w5Ncy2VHbTokxTd7Rg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-10T16:50:07Z"
  mac: ENC[AES256_GCM,data:sGASwGpVnp9XeUb369M1dDALReaKBDqXAJdhWtGPKzO4L/pEmkjHoBIquj9oyveePcEuiybMhTw8os+Dzx45IclA6gptHfPiXcbjNnsRv9tXPiFc5Z6slY62B1ck/8IEO6K3GOpLb5XwCc01MljmLdmo0izS35z8Y5ZelNhhDRI=,iv:d/rQbPy15wwtHdbrLvLhxn2JCNQ+R+DA+8LsvkYFD24=,tag:DpaIGwlL17YdcSFZB8jUxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
