apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: secrets
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: cert-manager
stringData:
    cf_token: ENC[AES256_GCM,data:ybJnKcS1OJ0ekdLo71kLqZPgORB8FRn7PxVRS18dK2r6okZjdIFBaA==,iv:MyBIDMUWHhkTisikNi1aBcUNNeMdqWzIdQ/QCM7vuOw=,tag:/R7A2bCwbC6MVvkAuOPRYA==,type:str]
type: Opaque
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIORbL1oxobb9kacZtHn4eH/JXOnb/h9eJzukcNTVGkkZ 3vabun@pm.me
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFZkU1BidyBnQTNt
            UEVRa1dzemVwWjZ6UEpZc1JlQS9EcDREeTRkWFZPcTdpQk9acWlJCk12ZVcrMUtq
            WmtOdFFKZ3VIWENPckFCRlR0cWo5RU44SnYrMWlIOGFPUDgKLS0tIExSWjh6QzFq
            OFdEZTBINk1uVERUZnAzYmMxek96VkYwV0RYTjZRZHJmTDQKjs2r4tfS/LLT5dZw
            XAcdcfGvHDhzhAhzC5SGZQU3Q8EaML77n41mo92zBW/TG+Ew/PxceSTJFfXRsWRW
            kr3ZFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15z7sk0c6teshxjaesjmvmthhwuhlfyucg8uxktazxvwcjtc8kvas8ft7k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNVQ4LzBtVzVaeHp4VlVU
            YzM0NCsrQjUrS1k5NkYyUG1vaW15REJlOTA0CkdjdnpQQUU1VmQ1MitNbzR1UnQy
            ZGRNRGtjb2FVUDdORytjT1Q1N284dWcKLS0tIDlqWURuWitlTnRYTjVMZHlZcGlH
            T2ZZdmpxbkxqYTFqanFHMm5qbGRxUXMKt96uWix4flcW/lRl/fvNSef6kH2OcUZ1
            wmPlB9+HMOO9m7XK9k6C5QUN0EpWTXfv492YchXutMAnPExdlarCNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T20:58:33Z"
    mac: ENC[AES256_GCM,data:+gd+me2DW+rFHXob4e+CfKJ4VuDvyxVuKL5Yu3BnMutrcjKVLMqz8XC2+BEeVuGQg8rcjxT6FaTdswsdk0BELOueGcRBL5lviQRlZwqfPO7V11PVJk3wqcLMylolGr5iXTbjZdVQ+fyzSm/dKIa46vOImbL2q8HDeWychhDtjBk=,iv:7P95A3JOx6n7OFjYFEnWd4srtREZuAyLZSAMQV5mLpM=,tag:vJAEyW8xAygOavFS3zXiyg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
