apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: secrets
  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: cert-manager
stringData:
  cf_token: ENC[AES256_GCM,data:sONGiulHvrccEeGX80+27FLXoRajWAm9mPFQKM3/dS1Fq1AP16a9bA==,iv:poSplFsH+x/A3qc36UNg/gMpSvXFc8S21MzPuFmUZcI=,tag:hb9UMlh75ieQvaUl61dcrQ==,type:str]
type: Opaque
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIORbL1oxobb9kacZtHn4eH/JXOnb/h9eJzukcNTVGkkZ 3vabun@pm.me
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFZkU1BidyArQ0xq
        elhKQUJHaVNZWnlLQzJKa1dDK2hZS0VkN2pqZ3VPNjNlT2VteVVBCm1HUVBNRmhW
        amhPQ1lubjlrNXRUUWNmdDNuTnJiL2tCQncxbm8vT1YyelEKLS0tIC9wajdjUlo5
        TlVPa2VxL1VCMm1LSEtIalNDaldWM0cxYXlLa2FQNTU4MkkKdgb+Pi7NmAzV0GFM
        4GRAhDaWkB0n0JMSTEWSLVqOuaM8C00NMwyt9J+Z6aPzQFF+Yeexzt+cO6t1fQnH
        KK4RgQ==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age15z7sk0c6teshxjaesjmvmthhwuhlfyucg8uxktazxvwcjtc8kvas8ft7k5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMWpid05zQjUzRDErMUpy
        UUtLSkdVem9tWmIyc1dqMTZacllta215cXpRClNTL1R5V3V6cDUvTWdFYURtUmpK
        ZzRPVVZBNWVobGRTc0lsSmJMeHZBbzQKLS0tIDFHcVhTSVd6WGNjcVNsc2Z1NGc2
        M0ptREhCajg3aFNrakp6M1F6dzdjUmMKzEnnkj/eMJfcOH4HMd6E6mHwo6/Ko7pk
        +fVVctm8rsqvFdKttJk0duj8sv1da7TIkQOHV6BSUVB4uM3b/zsXAg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T20:22:05Z"
  mac: ENC[AES256_GCM,data:iK96UVLtGpHH5bkl6qv1sFICPB+kzpFS7FyqKuW8iU6MooWgrpUr66IbOTE1Xj9DoibNEa5RxLmFgeZEh3Y53teqbVK5pYj5+F3CPTcxfmb0nZrLvjmSm6qBWg+T96lOKPq8jK6QvwcbyjfxEF8TfEI8t3pGXZPiRTUboSg17nM=,iv:2u1c8OZnfXHD+2Z5V2CQ+wWGe1aFHe2CP4cNnLv82ME=,tag:KIbh6hehdgVdKGg+294JPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
