apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
stringData:
  cf_token: ENC[AES256_GCM,data:cpa1imB7vm2YNE5cWP5Tqm/OIT2UcJWCOdhU2cp3pUEwkhAhvWatLg==,iv:eaNGCClhowZ9BbP4J2i1BlUXO5fRLnb6/94yiUjM/Y8=,tag:T81QqbljomsdaSJtKCfHDw==,type:str]
type: Opaque
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIORbL1oxobb9kacZtHn4eH/JXOnb/h9eJzukcNTVGkkZ 3vabun@pm.me
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFZkU1BidyBFUldQ
        azhNdzgxQkJBWkFqSnFkd2pZeVFDaSt5THg5bzE1RTR1OWMwdVRZCmpta0dnaDlC
        WFpCMkJ0ZGdCSVdKRW9BNjFEWUJGaitJUzU0TEpnZDY1YkEKLS0tIG1NRTU5WGZu
        VThjRjhUUC9mVzJ0Q1IyTGF0MG9XcHF4aUk0Z0NmNXhTVGcKGL4pjBlgYw+rxZS9
        WA/aE1Kq5t0tcTovSCr2s5IhisXIYEKjkxeJSnPGB7urgaZyuQtCcNfU5CLUIjzL
        kSFunw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age15z7sk0c6teshxjaesjmvmthhwuhlfyucg8uxktazxvwcjtc8kvas8ft7k5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaHMyUVVXd05pMGZIcGZ0
        dzdtZm85TkRvYTY0aGNtalNGekhXNWY5MUc4CklkcllpWExMUnl3NjdzUGxjQkJi
        VVlZdCtMRDVVUnNtY1BmOEpDYTd4YUEKLS0tIGd1MThzR1UzL0srd0V0cE1GZ0dX
        SW0yR29HbW5rZ3dBYzRLVjhvaWFaWlkKtM+s3LJKB54wv1935t2ZmOAXd2XlES+8
        WNujzPp0sEUQin2ICwGzflDEtySzLr0nOoJQTMzzAQgEkKnrhX4xiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-04T20:53:46Z"
  mac: ENC[AES256_GCM,data:RztaCATyUuenrYPfzeQd1WYdQoMGM9PWnS2s+SwZwnlJhyTNCjSEUVDAkXjtPITxXbpYsI8e8GC35O9pYobfAl17Or+jcobTBxx0lPuR0BvG6NkeKknixboEVocUgnBYCVWPN9AcDuQSoPnKkQeJ/D+3fwGchxCVEYhbR88+Q/c=,iv:wisRM0UDdFVc9L0YZMVwpfZLy4JeEdo6H72qyJ+ZLLk=,tag:QE0yxxs7QEMvFcqhKGZ9Zg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
