apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: secrets
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: external-dns
stringData:
    cf-token: ENC[AES256_GCM,data:8Zzlzo1gXPst1WeGG3cOAVA7bxKRvDPTdsyKrg5Aj+NWFUh3bg83Bg==,iv:dyhquhY9PsPFjH7Q3C9Gf4AQFmTWpCpL62VPdrJkYfM=,tag:R2qlDHoBtgl8ydYgBwHazg==,type:str]
type: Opaque
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIORbL1oxobb9kacZtHn4eH/JXOnb/h9eJzukcNTVGkkZ 3vabun@pm.me
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFZkU1BidyAydFdW
            MUlTSnR4dnFkZjY4TG9kU0NoOU1seHlKRmJNYTdwQmdVaDRzWmdZClp2SmZxYWRa
            UW9VZyt3Y29mL2o0Ni9DRGZMUllQOGFoaGxGK01iNmMyUmcKLS0tIDlqS1dyRkJW
            R2VCRVhpUTZ2MXNpN2JCQ1lnZ2xnYmFZcmJ4ZzIzWjdiSW8KyS6INcd4vWurX9SN
            5LKuVkp0H2Tz0carLxSoibWlKiZLrxDdEiWSiiPygZxtaf5hMMzjf7lnklIfOiO9
            SSVXEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15z7sk0c6teshxjaesjmvmthhwuhlfyucg8uxktazxvwcjtc8kvas8ft7k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUGdkTWJCejBtSWlXYm43
            d2xsT2N4cWRsRGtjWW5BQ3FqelhiNTA2d0NvCkgzMGZ4NEt5N0ZqSkhQL3V6bVdD
            UVJ0amQraVo4TmJDbEJwOFhxazlYTkUKLS0tIGE5cWRVU21GaTVCUlB3ZjdZTW9j
            V0JZYVFGd3ZwYmN4OXJteHgxT3dHT3MKDAYPosQuAlwk5JgHKWiZukiES+b449YO
            nOPmlUU+7IXJP/pe5R+mGQjeH2qDoMoj/RtJ33snN4wDqKVJEQFJhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T20:58:46Z"
    mac: ENC[AES256_GCM,data:MOra+72tHFvDUYiPWAysJRU0gXsaUANv7PTf/pn+lM/CWwmM9t7ADxBL+91LZuD+gCQd4W4ompqek0ipMZjyeY/4mbwbuHyrFUcEtG4E2koQFFyy0WN6QGOM6C3ku9TsLRA1Zyr50G8xmHE5pe+ptduCHVeXkVsQ5cBXTVym0aU=,iv:yCFxGl0SfMbJbxgn505l3OzEpohGrPebI/BHtXVai0I=,tag:ztBTltX/Wayv6/RweekRrQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
