apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: secrets
  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
  reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: external-dns
stringData:
  cf-token: ENC[AES256_GCM,data:7o0U14En3fWrsu5vu0PNPKG0ZzZODKBEIbaJCp4Gv+yCcaOx6FlLeQ==,iv:DQ9qBCG/9QWMwA8WrHcnakpsvV0PVAN16zNBnE76zbs=,tag:ucJyoLu6kg3fiAiTkdqRfw==,type:str]
type: Opaque
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIORbL1oxobb9kacZtHn4eH/JXOnb/h9eJzukcNTVGkkZ 3vabun@pm.me
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFZkU1BidyBGY1NU
        OGc4d0p3T1RZK3hBTXQ2WmJ4cm1TS3V6WXh1OWJhUlBpUm5ZeVRNCmthQTV6YVhk
        MjZyajlmeHFuUE8rdm9YU2VjdjJDdDZwaG1teVo3amNWSkEKLS0tIGd6NHRnSkNM
        TFlmZ2lUS3h3VWxFc0VydTZydk9hYWdjbHM2dmZ1K0RWaGMKw9ivuFXWvwjyLgya
        jI2TeS2684JezcVVycLULAspER1aBdAeim6HCHCKM8uiFl1S0V4RqpU7Xd3VHf/q
        hJTqNA==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age15z7sk0c6teshxjaesjmvmthhwuhlfyucg8uxktazxvwcjtc8kvas8ft7k5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dS92MGZaVGs4QldhQkJD
        ZzVicHVIOGsvS0pmWC91VHVjdXpPRmhHSEdJCmJRUENmT3g4VEp0aDhUWGJCbjhz
        alh3YWV0K3BhRDFGZ1pwNzhHaVRSQ28KLS0tIGdQdU9MdjBkZ0RwdWdIWGZ5Uith
        VjFWTTZWanU5MFN2aU5QdjlYRE1QSTQKf/Io6dXrMbMUwzUqQEdG8LS2+HKQbp7Y
        qD+jpvQGvtmYti6IOeFPS7Wu/gerS4QuSKN+zNdG2S+WY+gurpdVGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T20:28:58Z"
  mac: ENC[AES256_GCM,data:yEv9BhjrvbFx/3zWZYGKh5HVSHR6tXpBXEIFFHe1v7lrRaMPGhtdzbGRfo2WqyEeF0q3Wqe0H2jhg0K2ibX6An13OZRP9eybQRsjPm9S2HY6s53iBeWS3KH3XNsXMDcsfLPXQ2+QZJqFF/zRcxIOg5HlHPedE8FG3ZFXQSlwag0=,iv:CX8ovOaEZPuoxupq8CbPhRvm1SG+hahLdYkK+oqxSiw=,tag:fzqHMr4lfEfat+O1QhtqRw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
