apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token 
  namespace: external-dns
stringData:
  CF_API_TOKEN: ENC[AES256_GCM,data:mlgcnVm3E4CkeOJwaLyg6xfE5idFNk+lZXdZnZEit60YJpHtJfgrHA==,iv:s2nc2mYAvp+IZrQXssHDQP4vopuxYs4ZwSDfgHH5pG0=,tag:Q+dI0dkjHN/hlJ/Gf8Shsg==,type:str]
type: Opaque
sops:
  age:
    - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIORbL1oxobb9kacZtHn4eH/JXOnb/h9eJzukcNTVGkkZ 3vabun@pm.me
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFZkU1BidyBzWjgv
        aFd1QjNXS010c0c2Si82TVFBa2s1UGFDeTF1R3p1OUk0ZlAxRUV3CnI1QTFzbWNi
        eEZrbXMwT0MvK3c4QklYYjJLY2xReGIzRTJhMGJQK2VRYm8KLS0tIFJUWG9mVEdM
        SHQxdlNSSHJzYURjNjZWYzJVSTNUM1dGejdqRHVKaGN6UWcKmhuUCl5rfwQOd31J
        tI8WhNo5w54ToonfZYSxwKWVlQJZLYrWe+a9FyvDv/hfcZpmnsqk6GVp0kLggaeE
        SqrsGw==
        -----END AGE ENCRYPTED FILE-----
    - recipient: age15z7sk0c6teshxjaesjmvmthhwuhlfyucg8uxktazxvwcjtc8kvas8ft7k5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Y1RaOUtKVlN0cjdwSVRY
        d0RSSy9wSzRFVTF4UElzQlBiL3drNFp0YmtFClRQSFdCb0ZOaDhuMHYxRzlJME1p
        eXZBKzdaZmRvblAyVnhIS2lHSjNJYVUKLS0tIHhsbGRLZVY3SHYzQ3VwVUVmMnZL
        KzhOVFM1aGMzdjNtZFJBeGUzNlhBZzAKGy1UawMqPiV/6WGETVw/+ikKE/n7j/LH
        Qgx0oY/brZF6EOOWX22wdJbVz1dJ8DAzLfk5QmQUTO57iiRUCWzOgg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-21T18:46:55Z"
  mac: ENC[AES256_GCM,data:/fm/JU+CITza5Mwait3Bg4VlFaBnZMQOgjnkClln190rHUW4YYA3xk1F9J4V9ruFuieeQT+rNBaCLyaKdcXBfF1jKqGCHCVEZD3qdHx8yfxmuIQ2y/XDTf91x8lYmT0mCnNpHxT94Qn9H9h62pdpN8TDqeiqsBli7mFdrxLLO4E=,iv:K8441e/kbhqyPaUq/GJbP6o3q3CXk1VmbirtyJpqPOg=,tag:rrjmsbXUFMGs+zTuS9ZX6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
