apiVersion: v1
kind: Secret
metadata:
    name: pihole-password
    namespace: secrets
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: pihole,external-dns
stringData:
    pihole-password: ENC[AES256_GCM,data:/mhifymix89Cl2e9Q2HHPA==,iv:SeWHkdiQ8KCpxa3qfn1PElAKH3NJqFJk/X6aGVn+xyk=,tag:05onPFXzmOtG6LDnnDrRzA==,type:str]
type: Opaque
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIORbL1oxobb9kacZtHn4eH/JXOnb/h9eJzukcNTVGkkZ 3vabun@pm.me
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IFZkU1BidyAzZWxK
            eWxqZlVtc3d5c1JhbE96V2tCYlk5RnVkbllDL2g4T3NYVndPQUJzCnBPNlFmOW0w
            UjJwWEptVmI0WmNFQzVWRHJQZ2hSVUVhenU3bDRlTHlwQmcKLS0tIEN1UXl1ekdy
            RnJkeWpJZU9SR3c3QTZaT1VaY1ZzM2RJKzhPbHAwU2cybFUKz6O/BIt8YhrwTsHX
            +k/cujvMoOHrjedRzCwudDFgPFuF3QYOlupBBOinUbimPMQRWqsk6cbhVZlMjxDK
            qdOHcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15z7sk0c6teshxjaesjmvmthhwuhlfyucg8uxktazxvwcjtc8kvas8ft7k5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPN3hxQzcxd1J0Y1RQYkow
            YjFKR3JvZHZtWGQxVlB3ckN5emNwdUU4cUU0CmYrT3RzTHVFVnpyaTZFMWVFTFMr
            TnZBM1JTK0NpMHA3SnpkbzZISUpUQlkKLS0tIDRMdEhXYjlKL0Q2RmxUVUpBRDJZ
            ekVIUmJ2MkttU2hlT3NhblUyS0lqSTQKFljeZnP+qS/oNwsW8EJOJP31yxyIchaM
            3NtMeCFf/5R5dA7QkevtFGAe74GJwCCy1vVY6RRMLKnXtlKa1BxXsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T20:55:11Z"
    mac: ENC[AES256_GCM,data:GVuToUEW6lGid1I5ZqRfjYJsucPB2JRkvnETQPME3dIX31FXNYsIi7Ui/d5BaUaec95P3k6GS+dY2xEWKcwqdaLhPuRieT9TWHij/TKLa+tHD7izGBMDpuV+7PJhSEifNgRzxcvIxp6bKDDcgde483tR3gpWCKrnvMUfH1FAYU4=,iv:hMeh0elP51lZ2FFRlvxPPmFHIakbC8fmu1w5JTooJJA=,tag:rFhj7i6IdxkvcoR4SogN0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
