# /// script
# requires-python = ">=3.13"
# dependencies = [
#     "chevron",
# ]
# ///

import chevron
import json
import os
import sys

FILE_PREAMBLE: str = """# DO NOT EDIT - THIS IS AN AUTOGENERATED FILE
#
# To change this file, edit the template at cluster-config-template.yaml or change the 
# variables found in the config.json file in the repository root, then regenerate by 
# running `uv run kubernetes/generate_config.py $CLUSTER_NAME` from the repository
# root."""

def apply(cluster: str):
    script_dir = os.path.dirname(os.path.abspath(__file__))

    vars_file = os.path.join(script_dir, "../config.json")
    template_file = os.path.join(script_dir, f"./fluxcd/clusters/{cluster}/cluster-config-template.yaml")
    target_file = os.path.join(script_dir, f"./fluxcd/clusters/{cluster}/cluster-config.yaml")

    with open(vars_file, mode="r") as f:
        config = json.load(f)

    with open(template_file, mode="r") as f:
        res = chevron.render(f, config)
        generated_file = FILE_PREAMBLE + "\n\n" + res

    with open(target_file, mode="w") as f:
        f.write(generated_file)



if __name__ == "__main__":
    cluster = sys.argv[1]
    apply(cluster)
