---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: persistence-lpp-configs
  namespace: flux-system
spec:
  interval: 60m
  timeout: 3m
  retryInterval: 2m
  prune: true
  wait: true
  path: ./kubernetes/fluxcd/infra/base/configs/local-persistence
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-config
        optional: false
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: persistence-lpp-controller
  namespace: flux-system
spec:
  interval: 60m
  timeout: 3m
  retryInterval: 2m
  prune: true
  wait: true
  path: ./kubernetes/fluxcd/infra/base/controllers/local-path-provisioner
  sourceRef:
    kind: GitRepository
    name: flux-system