---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  chart:
    spec:
      chart: traefik
      version: "v37.1.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    # Verbose logging
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
        addInternals: true
    # Use Gateway API
    providers:
      kubernetesIngress:
        enabled: false
      kubernetesGateway:
        enabled: true
        experimentalChannel: false
    ingressClass:
      enabled: false
    gateway:
      enabled: false
    gatewayClass:
      enabled: true
      name: "traefik"
    # BasicAuth middleware for dashboard
    extraObjects:
      - apiVersion: traefik.io/v1alpha1
        kind: Middleware
        metadata:
          name: dashboard-auth
        spec:
          basicAuth:
            secret: dashboard-auth-secret
    # Enable dashboard
    ports:
      dashboard:
        port: 8888
        protocol: TCP
        expose:
          default: true
        nodePort: 30002
      web:
        port: 80
        protocol: TCP
        expose:
          default: true
        nodePort: 30000
      websecure:
        port: 443
        protocol: TCP
        expose:
          default: true
        nodePort: 30001
    api:
      dashboard: true
      insecure: true
    # ingressRoute:
    #   dashboard:
    #     enabled: true
    #     matchRule: Host(`dashboard.docker.local`)
    #     entryPoints:
    #       - https
    #     middlewares:
    #       - name: dashboard-auth